spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&useSSL=true
    username: root
    password: qwe123
    #schema: database/import.sql
    #sql-script-encoding: utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver
  mvc:
    throw-exception-if-no-handler-found: true
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  #config-location:classpath: /mybatis-config.xml


mybatis:
  mapper-locations: classpath*:com/wwp/mapper/xml/*Mapper.xml
  type-aliases-package: com.wwp.entity
  config-location: classpath:/mybatis-config.xml

server:
  error:
    path: /error

netty:
  port: 10000